package com.demo.bank.bean;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.JoinTable;
import jakarta.persistence.OneToMany;
import jakarta.persistence.OneToOne;
import jakarta.persistence.OrderColumn;
@Entity
public class Account {

	@Id
	@GeneratedValue(strategy = GenerationType.TABLE)
	int accountid;//autogenerated
	@OneToOne(cascade = CascadeType.ALL)
	@JoinColumn(name="cust_Id", referencedColumnName = "id")
	Customer cutomer;
	
	@OneToMany(cascade = CascadeType.ALL)
	//@JoinTable(name="Account_TransactionJoin", joinColumns = @JoinColumn(name="accountid"),
	//inverseJoinColumns = @JoinColumn(name="transactionid"))
	@JoinColumn(name = "accountid")
	@OrderColumn(name = "type")
	private Collection<Transaction> transaction = new ArrayList<Transaction>();
	
	Double currentBalance;
	public Account() {
		super();
	}
	public Account( Customer cutomer,  Double currentBalance) {
		super();
		this.cutomer = cutomer;
		//this.transactions = transactions;
		this.currentBalance = currentBalance;
	}
	public Account( Customer cutomer, List<Transaction> transaction, Double currentBalance) {
		super();
		this.cutomer = cutomer;
		this.transaction = transaction;
		this.currentBalance = currentBalance;
	}
	public int getAccountid() {
		return accountid;
	}
	public void setAccountid(int accountid) {
		this.accountid = accountid;
	}
	public Customer getCutomer() {
		return cutomer;
	}
	public void setCutomer(Customer cutomer) {
		this.cutomer = cutomer;
	}

	public Collection<Transaction> getTransaction() {
		return transaction;
	}

	public void setTransaction(Collection<Transaction> transaction) {
		this.transaction = transaction;
	}
	 
	public Double getCurrentBalance() {
		return currentBalance;
	}
	public void setCurrentBalance(Double currentBalance) {
		this.currentBalance = currentBalance;
	}
	@Override
	public String toString() {
		return "Account [accountid=" + accountid + ", cutomer=" + cutomer 
				+", transactions=" + transaction + ", currentBalance=" + currentBalance + "]";
	}

	
	
	
}
