package com.demo.bank.bean;

import java.time.LocalDate;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
@Entity
public class Transaction {

	@Id
	@GeneratedValue(strategy =  GenerationType.TABLE)
	int transactionId; //autogenerated
	LocalDate transactiondate= LocalDate.now() ;
	String transactionType;
	Double transactionAmount;
	Double closingBalance;
	
	public Transaction() {
		super();
	}

	public Transaction(LocalDate transactiondate, String transactionType, Double transactionAmount,
			Double closingBalance) {
		super();
		this.transactiondate = transactiondate;
		this.transactionType = transactionType;
		this.transactionAmount = transactionAmount;
		this.closingBalance = closingBalance;
	}
	
	public Transaction(String transactionType, Double transactionAmount, Double closingBalance) {
		super();
		this.transactionType = transactionType;
		this.transactionAmount = transactionAmount;
		this.closingBalance= closingBalance;
	}

	public int getTransactionId() {
		return transactionId;
	}
	public void setTransactionId(int transactionId) {
		this.transactionId = transactionId;
	}
	public LocalDate getTransactiondate() {
		return transactiondate;
	}
	public void setTransactiondate(LocalDate transactiondate) {
		this.transactiondate = transactiondate;
	}
	public String getTransactionType() {
		return transactionType;
	}
	public void setTransactionType(String transactionType) {
		this.transactionType = transactionType;
	}
	public Double getTransactionAmount() {
		return transactionAmount;
	}
	public void setTransactionAmount(Double transactionAmount) {
		this.transactionAmount = transactionAmount;
	}
	public Double getClosingBalance() {
		return closingBalance;
	}
	public void setClosingBalance(Double closingBalance) {
		this.closingBalance = closingBalance;
	}
	@Override
	public String toString() {
		return "Transaction [transactionId=" + transactionId + ", transactiondate=" + transactiondate
				+ ", transactionType=" + transactionType + ", transactionAmount=" + transactionAmount
				+ ", closingBalance=" + closingBalance + "]";
	} 
	
	
	
	
}
